# Generated by Django 4.2.1 on 2023-05-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_contrent_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='contrent',
        ),
    ]
