# Generated by Django 4.2.1 on 2023-05-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_clientes_delete_contrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='Cantid_noches',
            new_name='Cantidad_noches',
        ),
    ]
