# Generated by Django 4.2.1 on 2023-05-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_cantid_noches_clientes_cantidad_noches'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_espacios', models.IntegerField()),
                ('Importe_cobrado', models.FloatField()),
                ('Periodo_cobrado', models.CharField(max_length=125)),
                ('Fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
