# Generated by Django 3.2 on 2023-05-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ingresoespacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Apellidos',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cantidad_noches',
            new_name='cantidad_noches',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Ciudadano',
            new_name='ciudadano',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Documento_identidad',
            new_name='documento_identidad',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Fecha_entrada',
            new_name='fecha_entrada',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Fecha_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Fecha_salida',
            new_name='fecha_salida',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Info_registro',
            new_name='info_registro',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Ingreso_almuerzo',
            new_name='ingreso_alojamiento',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Ingreso_arrendamiento',
            new_name='ingreso_total',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='No_de_orden',
            new_name='no_de_orden',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Objeto_arrendamiento',
            new_name='objeto_arrendamiento',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Recibo_pago',
            new_name='recibo_pago',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='Ingreso_desayuno',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='Ingreso_total',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='id',
        ),
        migrations.AddField(
            model_name='clientes',
            name='ingreso_almuerzo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ingreso_desayuno',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('timefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.timefield')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
            ],
            bases=('polls.timefield',),
        ),
        migrations.AddField(
            model_name='clientes',
            name='timefield_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.timefield'),
            preserve_default=False,
        ),
    ]
