# Generated by Django 4.2.1 on 2023-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_apellidos_contrent_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrent',
            name='Pasaporte',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
