# Generated by Django 4.2.1 on 2023-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_contrent_pasaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrent',
            name='No_de_orden',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
