# Generated by Django 3.2 on 2023-05-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20230529_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadania',
            fields=[
                ('timefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.timefield')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('polls.timefield',),
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='ciudadano',
        ),
        migrations.AddField(
            model_name='clientes',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ciudadania'),
        ),
    ]
