# Generated by Django 3.2 on 2023-05-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20230529_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ingreso_alojamiento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ingreso_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
