# Generated by Django 4.2.1 on 2023-05-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_contrent_no_de_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrent',
            name='No_registro',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
