# Generated by Django 4.2.1 on 2023-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20230529_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ingreso_alojamiento',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ingreso_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
