# Generated by Django 4.2.1 on 2023-05-11 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_contrent_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_orden', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=125)),
                ('Apellidos', models.CharField(max_length=255)),
                ('Ciudadano', models.CharField(max_length=125)),
                ('Documento_identidad', models.CharField(max_length=125)),
                ('Objeto_arrendamiento', models.CharField(max_length=125)),
                ('Fecha_entrada', models.DateField()),
                ('Fecha_salida', models.DateField()),
                ('Importe_arrendamiento', models.FloatField()),
                ('Importe_servicio', models.FloatField()),
                ('Total_ingreso', models.FloatField()),
                ('Recibo_pago', models.IntegerField()),
                ('Estado', models.CharField(max_length=50)),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='contrent',
        ),
    ]
