# Generated by Django 4.2.1 on 2023-05-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_clientes_ingreso_alojamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoespacio',
            old_name='Cantidad_espacios',
            new_name='cantidad_espacios',
        ),
        migrations.RenameField(
            model_name='ingresoespacio',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='ingresoespacio',
            old_name='Importe_cobrado',
            new_name='importe_cobrado',
        ),
        migrations.RenameField(
            model_name='ingresoespacio',
            old_name='Periodo_cobrado',
            new_name='periodo_cobrado',
        ),
    ]
