# Generated by Django 4.2.1 on 2023-05-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_cantidad_espacios_ingresoespacio_cantidad_espacios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosArr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle_gasto', models.CharField(max_length=500)),
                ('concepto', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=125)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('importe', models.FloatField()),
            ],
        ),
    ]
