# Generated by Django 4.2.1 on 2023-06-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_gastosespacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='citizenship',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='objeto_arrendamiento',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
