# Generated by Django 3.2 on 2023-06-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_clientes_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ciudadania'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='objeto_arrendamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.rooms'),
        ),
    ]
