# Generated by Django 3.2 on 2023-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20230602_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='price',
        ),
        migrations.AddField(
            model_name='rooms',
            name='espacio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='habitacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
